name: .NET Build (Universal)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./AstroFlare.Compiler/AstroFlare.Compiler.csproj
    - name: Build
      run: dotnet build --no-restore ./AstroFlare.Compiler/AstroFlare.Compiler.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./AstroFlare.Compiler/AstroFlare.Compiler.csproj
