name: .NET Test (AstroFlare.Tests)

on:
  push:
    paths:
    - 'src/*'
    branches: [ main ]
  pull_request:
    paths:
    - 'src/*'
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: 'dotnet build'
      run: dotnet build ./src/AstroFlare.sln
    - name: 'dotnet test'
      run: dotnet test ./src/AstroFlare.sln
